var arr = [1,2,4,6,8,10,12]

console.log(Math.min(1,2,4,6,8,10,12))
console.log(Math.max(1,2,4,6,8,10,12))
console.log (Math.ceil(4.67))
console.log (Math.round(4.46))
console.log (Math.round(5.6))
console.log (Math.pow (3, 3))
console.log (Math.floor (4.2))
console.log (Math.sqrt (9))

var d = new Date()
var d1 = new Date().getFullYear ()
var d2 =new Date().getMonth()
var d3 =new Date().getDate()
var d4 =new Date().getSeconds()
var d5 =new Date().getTimezoneOffset()
d.setFullYear(2024,1)
console.log (d)
console.log (d1)
console.log (d2)
console.log (d3)
console.log (d4)
console.log (d5)
d.setFullYear(2024,1)